'use client';

import Link from 'next/link';
import { useQuery } from '@tanstack/react-query';
import { Search } from 'lucide-react';
import { useSearchParams } from 'next/navigation';
import { Suspense, useEffect, useState } from 'react';
import type { SearchResult } from '@/types/quran';

export default function SearchPage() { return <Suspense fallback={<div className="mx-auto max-w-4xl px-4 py-10 text-muted sm:px-6">Loading search…</div>}><SearchContent /></Suspense>; }
function SearchContent() { const params = useSearchParams(); const [query, setQuery] = useState(params.get('q') ?? ''); const [submitted, setSubmitted] = useState(query); useEffect(() => { const timer = setTimeout(() => setSubmitted(query), 350); return () => clearTimeout(timer); }, [query]); const search = useQuery({ queryKey: ['search', submitted], queryFn: async () => { if (submitted.trim().length < 2) return []; const response = await fetch(`/api/search?q=${encodeURIComponent(submitted)}`); if (!response.ok) throw new Error(); return (await response.json()).data as SearchResult[]; }, enabled: submitted.trim().length >= 2 }); return <div className="mx-auto max-w-4xl px-4 py-10 sm:px-6"><p className="text-xs font-semibold uppercase tracking-[.16em] text-accent">Search the Quran</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">Find a verse, theme, or phrase.</h1><label className="mt-8 flex items-center gap-3 rounded-2xl border border-line bg-panel px-4 py-3 focus-within:ring-2 focus-within:ring-accent"><Search className="size-5 text-muted" /><input autoFocus value={query} onChange={event => setQuery(event.target.value)} placeholder="Try ‘mercy’, ‘patience’, or 2:255" className="w-full bg-transparent text-base outline-none placeholder:text-muted" /></label>{search.isFetching && <p className="mt-8 text-sm text-muted">Searching translations…</p>}{search.data && <div className="mt-8 space-y-2">{search.data.map(result => <Link href={`/reader/${result.surahId}#ayah-${result.verseNumber}`} key={result.key} className="block rounded-2xl border border-line bg-panel p-5 transition hover:border-accent/50"><div className="flex justify-between gap-4"><p className="font-medium">{result.surahName} <span className="text-muted">{result.key}</span></p><span className="text-xs font-medium text-accent">{result.translationId}</span></div><p className="mt-3 leading-7 text-muted">{result.text}</p></Link>)}</div>}</div>; }
